import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  fr: {
    // Header translations
    'home': 'Accueil',
    'rooms': 'Chambres',
    'dining': 'Restaurant',
    'about': 'À Propos',
    'gallery': 'Galerie',
    'contact': 'Contact',
    'book_now': 'Réserver',
    'book_now_mobile': 'Réserver Maintenant',
    'hotel_ruvubu': 'Hôtel Ruvubu',
    'buhumuza_cankuzo': 'Buhumuza, Cankuzo',
    
    // Restaurant page translations
    'restaurant_bar': 'Restaurant & Bar',
    'dining_at_buhumuza': 'Restauration à Buhumuza',
    'dining_description': 'Cuisine burundaise authentique et spécialités internationales, préparées avec des produits sélectionnés. Bar lounge moderne, boissons maison et paniers-repas sur demande.',
    'local_international_cuisine': 'Cuisine locale et internationale',
    'lounge_bar_lemonades': 'Bar lounge & limonades artisanales',
    'picnic_baskets': 'Paniers-repas pour vos excursions',
    'cuisine_quote': 'Une cuisine adaptée à tous les goûts.',
    'our_menu': 'Notre Carte',
    'select_category': 'Sélectionnez une catégorie pour explorer nos saveurs',
    'all': 'Tout',
    'burundian': 'Burundais',
    'international': 'International',
    'special': 'Spécial',
    'previous': 'Précédent',
    'next': 'Suivant',
    'page_of': 'Page {current} sur {total}',
    'no_items': 'Aucun élément de menu disponible pour cette catégorie.',
    'thirsty_after_visits': 'Envie de fraîcheur après vos visites ?',
    'bar_description': 'Découvrez notre bar moderne et nos limonades artisanales après Muyaga, Mishiha ou le Parc Ruvubu.',
    'book_table': 'Réserver une Table',
    'view_bar': 'Voir le Bar',
    'error': 'Erreur',
    'retry': 'Réessayer',
    'loading': 'Chargement...',

    // About page translations
    'about_us': 'À propos',
    'our_heritage_history': 'Notre Patrimoine & Histoire',
    'our_story': 'Notre Histoire',
    'heritage_hospitality': 'Patrimoine & Hospitalité',
    'hero_title': 'Plus qu\'un hôtel, un pont vers l\'âme de Buhumuza.',
    'hero_description_1': 'L\'Hôtel Ruvubu incarne l\'esprit d\'apaisement de Buhumuza. Un refuge pour voyageurs en quête de sérénité et d\'immersion culturelle burundaise.',
    'hero_description_2': 'Porte d\'entrée vers les trésors de l\'Est : église de Muyaga, eaux thermales de Mishiha et Parc National de la Ruvubu. Histoire, nature et culture à portée de main.',
    'hero_description_3': 'Chambres confortables, cuisine raffinée, bar convivial, jardins paisibles : l\'hospitalité burundaise dans chaque détail.',
    'inauguration': 'Inauguration',
    'opening_title': 'Ouverture Officielle',
    'opening_description': 'L\'Hôtel Ruvubu devient la référence de l\'hospitalité à Cankuzo.',
    'tours_title': 'Circuits Touristiques',
    'tours_description': 'Excursions vers Muyaga, Mishiha et le Parc de la Ruvubu avec guides locaux.',
    'discover_region': 'Découvrir la Région',
    'watch_video': 'Voir la Vidéo',
    'excellence': 'L\'Excellence',
    'serving_your_stay': 'Au Service de votre Séjour',
    'gastronomy_title': 'Gastronomie Professionnelle',
    'gastronomy_description': 'Fusion de saveurs burundaises et internationales par nos chefs qualifiés.',
    'cultural_experiences_title': 'Expériences Culturelles',
    'cultural_experiences_description': 'Excursions vers sites historiques et naturels avec accès privilégié aux guides locaux.',
    'burundian_lifestyle_title': 'Art de Vivre Burundais',
    'burundian_lifestyle_description': 'Jardins paysagers et espaces pour mariages, conférences et réceptions.',
    'discover': 'Découvrir',
    'buhumuza_treasures': 'Trésors de Buhumuza',
    'explore_jewels': 'Explorez les joyaux entourant l\'Hôtel Ruvubu',
    'historical_badge': 'Historique',
    'wellness_badge': 'Bien-être',
    'culture_badge': 'Culture',
    'adventure_badge': 'Aventure',
    'muyaga_church_title': 'Première Église de Muyaga',
    'muyaga_church_description': 'Berceau du catholicisme burundais depuis 1889. Architecture coloniale et spiritualité.',
    'muyaga_church_distance': 'À proximité immédiate',
    'mishiha_hot_springs_title': 'Eaux Chaudes de Mishiha',
    'mishiha_hot_springs_description': 'Sources géothermiques naturelles aux vertus curatives et relaxantes.',
    'mishiha_hot_springs_distance': 'Excursion d\'une journée',
    'musugi_cendajuru_title': 'Musugi Cendajuru',
    'musugi_cendajuru_description': 'Site historique de l\'arrivée des premiers missionnaires, mémoire vivante de la région.',
    'musugi_cendajuru_distance': 'Accès facilité',
    'ruvubu_park_title': 'Parc National de la Ruvubu',
    'ruvubu_park_description': 'Safari et observation de la faune : hippopotames, crocodiles, buffles et avifaune.',
    'ruvubu_park_distance': 'Circuit guidé disponible',
    'book_stay_circuit': 'Réserver mon séjour & circuit',
    'garden_image_alt': 'Jardins paisibles de l\'Hôtel Ruvubu à Cankuzo',
    'room_image_alt': 'Chambre spacieuse',

    // Rooms page translations
    'rooms': 'Chambres',
    'your_comfortable_base': 'Votre Base Confortable',
    'loading_rooms': 'Chargement des chambres...',
    'loading_error': 'Erreur de chargement',
    'fetch_error': 'Échec du chargement des chambres',
    'generic_error': 'Une erreur est survenue',
    'price_range': 'Fourchette de Prix',
    'all_prices': 'Tous les Prix',
    'under_50k': 'Moins de 50 000',
    '50k_100k': '50 000 - 100 000',
    '100k_150k': '100 000 - 150 000',
    'over_150k': '150 000+',
    'guest_capacity': 'Capacité d\'Accueil',
    'any_capacity': 'Toute Capacité',
    '1_person': '1 Personne',
    '1_2_people': '1-2 Personnes',
    '3_4_people': '3-4 Personnes',
    '5_people': '5+ Personnes',
    'room_type': 'Type de Chambre',
    'all_rooms': 'Toutes les Chambres',
    'suite': 'Suite',
    'standard_room': 'Chambre Standard',
    'family_room': 'Chambre Familiale',
    'twin_room': 'Chambre Twin',
    'bungalow': 'Bungalow Groupe',
    'sort_by': 'Trier Par',
    'most_popular': 'Les Plus Populaires',
    'price_low_high': 'Prix : Croissant',
    'price_high_low': 'Prix : Décroissant',
    'customer_rating': 'Évaluation Client',
    'room_size': 'Taille de Chambre',
    'people': 'pers.',
    'default_room_description': 'Chambre confortable avec toutes les commodités nécessaires.',
    'reviews': 'avis',
    'no_reviews_yet': 'Pas encore d\'avis',
    'book': 'Réserver',
    'view_details': 'Voir détails',
    'no_rooms_match': 'Aucune chambre ne correspond',
    'adjust_filters': 'Ajustez vos filtres pour voir plus d\'options.',
    'reset_filters': 'Réinitialiser les filtres',
    'view_more_rooms': 'Voir Plus de Chambres',

     // Contact page translations
    'contact': 'Contact',
    'contact_us': 'Nous Contacter',
    'connect_with_hotel': 'Connectez-vous avec l\'Hôtel Ruvubu',
    'contact_description': 'Votre porte d\'entrée vers l\'hospitalité de Buhumuza et les expériences du patrimoine culturel.',
    'map_title': 'Emplacement de l\'Hôtel Ruvubu à Cankuzo, Burundi',
    'open_in_google_maps': 'Ouvrir dans Google Maps',
    'location_title': 'Notre Localisation',
    'location_line1': 'Cankuzo, Province de Buhumuza',
    'location_line2': 'Burundi, Afrique de l\'Est',
    'location_note': 'Près de l\'entrée du Parc National de la Ruvubu',
    'call_us_title': 'Appelez-nous',
    'phone_line1': '+257 66 307 160',
    'phone_line2': '+257 69 671 060',
    'phone_note': 'WhatsApp disponible',
    'email_title': 'Envoyez-nous un Email',
    'email_line1': 'info@ruvubu-hotel.com',
    'email_note': 'Réponse sous 24 heures',
    'send_message_title': 'Envoyez-nous un Message',
    'send_message_description': 'Des questions sur nos chambres, visites patrimoniales ou installations événementielles ? Remplissez le formulaire et nous répondons sous 24h.',
    'full_name': 'Nom Complet',
    'email_address': 'Adresse Email',
    'phone_number': 'Numéro de Téléphone',
    'phone_placeholder': '+257 79 123 456',
    'country': 'Pays',
    'subject': 'Sujet',
    'select_subject': 'Sélectionnez un sujet',
    'room_booking': 'Réservation de Chambre',
    'heritage_tour_request': 'Demande de Visite Patrimoniale',
    'event_conference': 'Événement & Conférence',
    'restaurant_booking': 'Réservation Restaurant',
    'group_booking': 'Réservation de Groupe',
    'general_inquiry': 'Demande Générale',
    'feedback': 'Retour d\'Expérience',
    'your_message': 'Votre Message',
    'message_placeholder': 'Dites-nous comment nous pouvons vous aider à vivre l\'hospitalité de Buhumuza...',
    'newsletter_consent': 'Je souhaite recevoir les nouvelles et offres spéciales de l\'Hôtel Ruvubu',
    'send_message_button': 'Envoyer le Message',
    'how_to_find_us': 'Comment Nous Trouver',
    'address_label': 'Adresse',
    'address_details': 'Hôtel Ruvubu, Cankuzo\nProvince de Buhumuza, Burundi',
    'landmarks_label': 'Points de repère',
    'landmarks_details': '25 km du Parc National de la Ruvubu\n4 km de la Première Église de Muyaga\n25 km des Sources Chaudes de Mishiha',
    'transport_label': 'Transport',
    'transport_details': 'Transferts depuis Bujumbura possibles. Contactez-nous pour organiser le transport.',
    'quick_actions': 'Actions Rapides',
    'book_room': 'Réserver une Chambre',
    'view_rooms': 'Voir nos Chambres',
    'our_story': 'Notre Histoire',
    'gallery': 'Galerie',
    'immediate_help': 'Besoin d\'Aide Immédiate ?',
    'reception_24_7': 'Réception 24/7 prête à vous aider',
    'faq_title': 'FAQ',
    'frequently_asked_questions': 'Questions Fréquemment Posées',
    'faq_description': 'Questions courantes sur nos services et installations',
    'faq1_question': 'Comment se rendre à l\'Hôtel Ruvubu depuis Bujumbura ?',
    'faq1_answer': 'Depuis l\'Aéroport International de Bujumbura, il y a environ 4 heures de route jusqu\'à Cankuzo. Nous proposons des transferts sur demande. Vous pouvez aussi prendre un bus jusqu\'à Cankuzo puis un taxi jusqu\'à l\'hôtel.',
    'faq2_question': 'Quels modes de paiement acceptez-vous ?',
    'faq2_answer': 'Espèces (BIF, USD), virements bancaires, Visa, MasterCard. Pour les réservations internationales, des options en ligne sécurisées peuvent être proposées.',
    'faq3_question': 'Proposez-vous des visites guidées des sites patrimoniaux ?',
    'faq3_answer': 'Oui, visites guidées de Muyaga, Musugi Cendajuru, sources chaudes de Mishiha et Parc National de la Ruvubu. Guides locaux, transport et repas disponibles.',
    'faq4_question': 'Quelles installations pour les réunions d\'affaires ?',
    'faq4_answer': 'Salle de conférence (jusqu\'à 100 pers), WiFi, projecteur/son, paperboards, restauration, salles de sous-groupes et hébergement des délégués.',
    'faq5_question': 'Gérez-vous les restrictions alimentaires ?',
    'faq5_answer': 'Oui. Régimes végétarien, végétalien, sans gluten, halal et autres sur demande. Indiquez vos besoins lors de la réservation.',
    'learn_more_about_us': 'En savoir plus sur nous',
    'view_our_rooms': 'Voir nos Chambres',
    'follow_us': 'Suivez-nous',
    'connect_on_social_media': 'Connectez-vous sur les Réseaux Sociaux',
    'social_media_description': 'Restez informé de nos dernières nouvelles, offres et événements culturels',
    'tripadvisor_handle': 'Lire les avis',

    // Gallery page translations
    'all_categories': 'Toutes',
    'categories_fetch_error': 'Échec du chargement des catégories',
    'gallery_fetch_error': 'Échec du chargement des éléments de la galerie',
    'loading_gallery': 'Chargement de la galerie...',
    'refresh_page': 'Actualiser la page',
    'no_gallery_items': 'Aucun élément de galerie trouvé.',
    'load_more_photos': 'Charger plus de photos',
    'need_more_photos': 'Besoin d\'autres photos ? Contactez-nous',

    // Homepage Hero Section
    'hero_main_title': 'Hôtel Ruvubu, Votre Havre de Paix à Buhumuza',
    'hero_main_description': 'Découvrez l\'hospitalité burundaise à l\'Hôtel Ruvubu : chambres spacieuses, cuisine raffinée et service exceptionnel au cœur de Buhumuza.',
    'free_wifi': 'WiFi Gratuit',
    'restaurant': 'Restaurant',
    'gardens': 'Jardins',
    'book_now_hero': 'Réserver Maintenant',
    'discover_our_rooms': 'Découvrir Nos Chambres',
    'comfortable_rooms': 'Chambres Confortables',
    'km_from_national_park': 'Km du Parc National',
    'tourist_sites': 'Sites Touristiques',
    'exceptional_service': 'Service Exceptionnel',
    'warm_welcome_service': 'Un accueil chaleureux et un service impeccable. L\'Hôtel Ruvubu incarne véritablement l\'esprit de Buhumuza.',

    // Homepage About Section
    'welcome_to_hotel': 'Bienvenue à l\'Hôtel Ruvubu',
    'your_haven_of_peace': 'Votre havre de paix à Cankuzo.',
    'about_description_1': 'Nichée à Buhumuza, l\'Hôtel Ruvubu est votre refuge au cœur des trésors culturels et naturels du Burundi.',
    'about_description_2': 'Chambres spacieuses, restaurant aux saveurs burundaises et internationales, bar convivial, jardins avec limonades artisanales, espaces événementiels : tout pour votre confort.',
    'about_description_3': 'Découvrez l\'hospitalité légendaire de Buhumuza à chaque instant de votre séjour.',
    'authenticity': 'Authenticité',
    'local_hospitality': 'Hospitalité Locale',
    '24_7': '24/7',
    'customer_service': 'Service Client',
    'premium_services': 'Services Premium',
    'learn_more': 'En Savoir Plus',
    'view_rooms': 'Voir les Chambres',
    'number_one_hotel': 'N°1',
    'hotel_in_cankuzo': 'Hôtel à\nCankuzo',

    // Homepage Amenities Section
    'services': 'Services',
    'our_premium_facilities': 'Nos Installations Premium',
    'professional_restaurant': 'Restaurant Professionnel',
    'professional_restaurant_desc': 'Goûtez aux véritables spécialités burundaises et les saveurs de notre carte internationale, préparées avec des produits frais et locaux.',
    'qualified_chefs': 'Chefs Qualifiés',
    'local_specialties': 'Spécialités Locales',
    'magnificent_gardens': 'Jardins Magnifiques',
    'magnificent_gardens_desc': 'Évadez-vous dans nos jardins paysagers et savourez nos délicieuses limonades dans un cadre verdoyant et apaisant.',
    'green_spaces': 'Espaces Verts',
    'relaxation_areas': 'Zones de Détente',
    'event_halls': 'Salles d\'Événements',
    'event_halls_desc': 'Conférences, mariages et événements sur mesure avec l\'accompagnement de notre équipe professionnelle.',
    'wedding_hall': 'Salle de Mariage',
    'conference_rooms': 'Salles de Conférence',
    'tourist_services': 'Services Touristiques',
    'tourist_services_desc': 'Découvrez la région avec nos guides experts : sites historiques, merveilles naturelles comme la réserve naturelle de la Ruvubu.',
    'cultural_circuits': 'Circuits Culturels',
    'nature_excursions': 'Excursions Nature',
    'modern_bar': 'Bar Moderne',
    'modern_bar_desc': 'Savourez nos limonades artisanales, boissons locales et cocktails dans notre bar à l\'atmosphère conviviale.',
    'premium_drinks': 'Boissons Premium',
    'modern_ambiance': 'Ambiance Moderne',
    'warm_hospitality': 'Hospitalité Chaleureuse',
    'warm_hospitality_desc': 'Découvrez l\'hospitalité légendaire de Buhumuza à travers notre équipe dévouée à votre confort et à un séjour inoubliable.',
    'service_24_7': 'Service 24/7',
    'warm_welcome': 'Accueil Chaleureux',

    // Homepage Rooms Section
    'accommodation': 'Hébergement',
    'your_comfortable_base_home': 'Votre Base Confortable',
    'quality_accommodation_comfort': 'Hébergement de qualité et confort au cœur de Buhumuza',
    'per_night': '/nuit',
    'sqm': 'm²',
    'discover_all_rooms': 'Découvrir Toutes Nos Chambres',

    // Homepage Offers Section
    'offers': 'Offres',
    'discovery_packages': 'Forfaits Découverte',
    'special_offers_description': 'Offres spéciales pour découvrir la région et ses merveilles',
    'cultural_circuit': 'CIRCUIT CULTUREL',
    'buhumuza_heritage_circuit': 'Circuit Héritage Buhumuza',
    'heritage_circuit_desc': 'Inclut hébergement, visites guidées à Muyaga, Musugi Cendajuru, eaux thermales de Mishiha, et déjeuner avec cuisine locale.',
    'valid_all_year': 'Valable toute l\'année',
    'contact_for_prices': 'Contacter pour les prix',
    'nature_culture': 'NATURE & CULTURE',
    'park_culture_combo': 'Combo Parc & Culture',
    'park_culture_combo_desc': 'Combiné safari au Parc de la Ruvubu et sites culturels. Inclut frais de parc, visites guidées, hébergement et tous les repas.',
    'best_may_october': 'Meilleur Mai - Octobre',
    'events': 'ÉVÉNEMENTS',
    'wedding_event_package': 'Forfait Mariage & Événement',
    'wedding_event_package_desc': 'Forfait complet incluant location de salle, restauration professionnelle, hébergement des invités et matériels pour les cérémonie traditionnelle.',
    'book_3_months_advance': 'Réserver 3 mois à l\'avance',
    'custom_quote_on_request': 'Devis personnalisé sur demande',
    'get_quote': 'Obtenir un Devis',
    'reserve': 'Réserver',

    // Homepage CTA Section
    'experience_buhumuza_hospitality': 'Vivez l\'Hospitalité de Buhumuza',
    'cta_description': 'Vivez l\'esprit burundais à l\'Hôtel Ruvubu : confort, gastronomie et accès privilégié aux trésors naturels de la région.',
    'spacious_comfortable_rooms': 'Chambres spacieuses et confortables',
    'burundian_international_cuisine': 'Cuisine burundaise et internationale',
    'bar_landscaped_gardens': 'Bar et jardins paysagers',
    'event_conference_spaces': 'Espaces pour événements et conférences',
    'excursions_ruvubu_park': 'Excursions vers le Parc de la Ruvubu',
    'reserve_now': 'Réserver Maintenant',
    'contact_us_cta': 'Nous Contacter',
    'nature_culture_badge': 'Nature & Culture',
    'to_discover': 'À Découvrir',

    // Homepage Gallery Section
    'spacious_room': 'Chambre spacieuse',
    'cultural_experience': 'Expérience Culturelle',
    'discover_more_photos': 'Découvrir Plus de Photos',
    'close': 'Fermer',
    'click_outside_or_esc': 'Cliquez à l\'extérieur de l\'image ou appuyez sur Échap pour fermer',
    'luxury_room': 'Chambre de luxe',

    "booking": "Réservation",
  "reservation": "Réservation",
  "book_your_stay": "Réservez Votre Séjour",
  "select_room": "Sélectionner la Chambre",
  "guest_details": "Détails des Invités",
  "select_dates": "Sélectionner les Dates",
  "check_in": "Arrivée",
  "check_out": "Départ",
  "guests": "Invités",
  "adults": "Adultes",
  "children": "Enfants",
  "available_rooms": "Chambres Disponibles",
  "reviews": "Avis",
  "per_night": "par nuit",
  "standard_room_description": "Une chambre confortable avec toutes les commodités essentielles pour un séjour agréable.",
  "included_amenities": "Équipements Inclus",
  "guest_information": "Informations sur l'Invité",
  "first_name": "Prénom",
  "last_name": "Nom de Famille",
  "email_address": "Adresse Email",
  "phone_number": "Numéro de Téléphone",
  "special_requests": "Demandes Spéciales",
  "special_requests_placeholder": "Toute demande ou exigence particulière...",
  "payment_information": "Informations de Paiement",
  "cardholder_name": "Nom du Titulaire",
  "card_number": "Numéro de Carte",
  "expiry_date": "Date d'Expiration",
  "cvv": "CVV",
  "booking_summary": "Résumé de la Réservation",
  "nights": "nuits",
  "taxes_fees": "Taxes et Frais",
  "total": "Total",
  "includes_taxes": "Toutes taxes et frais inclus",
  "secure_booking": "Réservation Sécurisée",
  "secure_booking_description": "Vos informations de paiement sont chiffrées et sécurisées. Nous ne stockons jamais vos coordonnées bancaires.",
  "continue_to_details": "Continuer vers les Détails",
  "complete_booking": "Finaliser la Réservation",
  "free_cancellation": "Annulation gratuite jusqu'à 48 heures avant l'arrivée",
  "modify_selection": "Modifier la Sélection",
  "back_to_rooms": "Retour à la Sélection des Chambres",
  "check_in_out_times": "Heures d'Arrivée et de Départ",
  "need_help_booking": "Besoin d'Aide pour Votre Réservation?",
  "booking_assistance_description": "Notre équipe est disponible 24h/24 et 7j/7 pour vous aider avec votre réservation. Contactez-nous pour toute question ou arrangement spécial.",
  "call_us": "Appelez-nous",
  "contact_us": "Contactez-nous",
  "rooms": "Chambres",
  "booking_confirmation_message": "Merci pour votre réservation ! Un email de confirmation a été envoyé à votre adresse email.",
  },
  en: {
    // Header translations
    'home': 'Home',
    'rooms': 'Rooms',
    'dining': 'Dining',
    'about': 'About',
    'gallery': 'Gallery',
    'contact': 'Contact',
    'book_now': 'Book Now',
    'book_now_mobile': 'Book Now',
    'hotel_ruvubu': 'Hotel Ruvubu',
    'buhumuza_cankuzo': 'Buhumuza, Cankuzo',
    
    // Restaurant page translations
    'restaurant_bar': 'Restaurant & Bar',
    'dining_at_buhumuza': 'Dining at Buhumuza',
    'dining_description': 'Authentic Burundian cuisine and international specialties, prepared with carefully selected products. Modern lounge bar, house-made drinks, and picnic baskets available upon request.',
    'local_international_cuisine': 'Local and international cuisine',
    'lounge_bar_lemonades': 'Lounge bar & artisanal lemonades',
    'picnic_baskets': 'Picnic baskets for your excursions',
    'cuisine_quote': 'A cuisine to suit all tastes.',
    'our_menu': 'Our Menu',
    'select_category': 'Select a category to explore our flavors',
    'all': 'All',
    'burundian': 'Burundian',
    'international': 'International',
    'special': 'Special',
    'previous': 'Previous',
    'next': 'Next',
    'page_of': 'Page {current} of {total}',
    'no_items': 'No menu items available for this category.',
    'thirsty_after_visits': 'Thirsty after your visits?',
    'bar_description': 'Discover our modern bar and artisanal lemonades after visiting Muyaga, Mishiha or Ruvubu Park.',
    'book_table': 'Book a Table',
    'view_bar': 'View the Bar',
    'error': 'Error',
    'retry': 'Retry',
    'loading': 'Loading...',

    // About page translations
    'about_us': 'About',
    'our_heritage_history': 'Our Heritage & History',
    'our_story': 'Our Story',
    'heritage_hospitality': 'Heritage & Hospitality',
    'hero_title': 'More than a hotel, a bridge to the soul of Buhumuza.',
    'hero_description_1': 'Hotel Ruvubu embodies the calming spirit of Buhumuza. A refuge for travelers seeking serenity and Burundian cultural immersion.',
    'hero_description_2': 'Gateway to the treasures of the East: Muyaga Church, Mishiha hot springs, and Ruvubu National Park. History, nature, and culture at your fingertips.',
    'hero_description_3': 'Comfortable rooms, refined cuisine, cozy bar, peaceful gardens: Burundian hospitality in every detail.',
    'inauguration': 'Inauguration',
    'opening_title': 'Official Opening',
    'opening_description': 'Hotel Ruvubu becomes the hospitality reference in Cankuzo.',
    'tours_title': 'Tourist Circuits',
    'tours_description': 'Excursions to Muyaga, Mishiha, and Ruvubu Park with local guides.',
    'discover_region': 'Discover the Region',
    'watch_video': 'Watch Video',
    'excellence': 'Excellence',
    'serving_your_stay': 'Serving Your Stay',
    'gastronomy_title': 'Professional Gastronomy',
    'gastronomy_description': 'Fusion of Burundian and international flavors by our qualified chefs.',
    'cultural_experiences_title': 'Cultural Experiences',
    'cultural_experiences_description': 'Excursions to historical and natural sites with privileged access to local guides.',
    'burundian_lifestyle_title': 'Burundian Lifestyle',
    'burundian_lifestyle_description': 'Landscaped gardens and spaces for weddings, conferences, and receptions.',
    'discover': 'Discover',
    'buhumuza_treasures': 'Buhumuza Treasures',
    'explore_jewels': 'Explore the jewels surrounding Hotel Ruvubu',
    'historical_badge': 'Historical',
    'wellness_badge': 'Wellness',
    'culture_badge': 'Culture',
    'adventure_badge': 'Adventure',
    'muyaga_church_title': 'First Church of Muyaga',
    'muyaga_church_description': 'Birthplace of Burundian Catholicism since 1889. Colonial architecture and spirituality.',
    'muyaga_church_distance': 'In immediate proximity',
    'mishiha_hot_springs_title': 'Mishiha Hot Springs',
    'mishiha_hot_springs_description': 'Natural geothermal springs with curative and relaxing properties.',
    'mishiha_hot_springs_distance': 'One-day excursion',
    'musugi_cendajuru_title': 'Musugi Cendajuru',
    'musugi_cendajuru_description': 'Historical site of the arrival of the first missionaries, living memory of the region.',
    'musugi_cendajuru_distance': 'Easy access',
    'ruvubu_park_title': 'Ruvubu National Park',
    'ruvubu_park_description': 'Safari and wildlife observation: hippopotamuses, crocodiles, buffaloes, and avifauna.',
    'ruvubu_park_distance': 'Guided tour available',
    'book_stay_circuit': 'Book my stay & tour',
    'garden_image_alt': 'Peaceful gardens of Hotel Ruvubu in Cankuzo',
    'room_image_alt': 'Spacious room',

     // Rooms page translations
    'rooms': 'Rooms',
    'your_comfortable_base': 'Your Comfortable Base',
    'loading_rooms': 'Loading rooms...',
    'loading_error': 'Loading Error',
    'fetch_error': 'Failed to fetch rooms',
    'generic_error': 'An error occurred',
    'price_range': 'Price Range',
    'all_prices': 'All Prices',
    'under_50k': 'Under 50,000',
    '50k_100k': '50,000 - 100,000',
    '100k_150k': '100,000 - 150,000',
    'over_150k': '150,000+',
    'guest_capacity': 'Guest Capacity',
    'any_capacity': 'Any Capacity',
    '1_person': '1 Person',
    '1_2_people': '1-2 People',
    '3_4_people': '3-4 People',
    '5_people': '5+ People',
    'room_type': 'Room Type',
    'all_rooms': 'All Rooms',
    'suite': 'Suite',
    'standard_room': 'Standard Room',
    'family_room': 'Family Room',
    'twin_room': 'Twin Room',
    'bungalow': 'Group Bungalow',
    'sort_by': 'Sort By',
    'most_popular': 'Most Popular',
    'price_low_high': 'Price: Low to High',
    'price_high_low': 'Price: High to Low',
    'customer_rating': 'Customer Rating',
    'room_size': 'Room Size',
    'people': 'people',
    'default_room_description': 'Comfortable room with all necessary amenities.',
    'reviews': 'reviews',
    'no_reviews_yet': 'No reviews yet',
    'book': 'Book',
    'view_details': 'View details',
    'no_rooms_match': 'No rooms match',
    'adjust_filters': 'Adjust your filters to see more options.',
    'reset_filters': 'Reset filters',
    'view_more_rooms': 'View More Rooms',

    // Contact page translations
    'contact': 'Contact',
    'contact_us': 'Contact Us',
    'connect_with_hotel': 'Connect with Hotel Ruvubu',
    'contact_description': 'Your gateway to Buhumuza hospitality and cultural heritage experiences.',
    'map_title': 'Location of Hotel Ruvubu in Cankuzo, Burundi',
    'open_in_google_maps': 'Open in Google Maps',
    'location_title': 'Our Location',
    'location_line1': 'Cankuzo, Buhumuza Province',
    'location_line2': 'Burundi, East Africa',
    'location_note': 'Near the entrance to Ruvubu National Park',
    'call_us_title': 'Call Us',
    'phone_line1': '+257 66 307 160',
    'phone_line2': '+257 69 671 060',
    'phone_note': 'WhatsApp available',
    'email_title': 'Send Us an Email',
    'email_line1': 'info@ruvubu-hotel.com',
    'email_note': 'Response within 24 hours',
    'send_message_title': 'Send Us a Message',
    'send_message_description': 'Questions about our rooms, heritage tours, or event facilities? Fill out the form and we\'ll respond within 24 hours.',
    'full_name': 'Full Name',
    'email_address': 'Email Address',
    'phone_number': 'Phone Number',
    'phone_placeholder': '+257 79 123 456',
    'country': 'Country',
    'subject': 'Subject',
    'select_subject': 'Select a subject',
    'room_booking': 'Room Booking',
    'heritage_tour_request': 'Heritage Tour Request',
    'event_conference': 'Event & Conference',
    'restaurant_booking': 'Restaurant Booking',
    'group_booking': 'Group Booking',
    'general_inquiry': 'General Inquiry',
    'feedback': 'Feedback',
    'your_message': 'Your Message',
    'message_placeholder': 'Tell us how we can help you experience Buhumuza hospitality...',
    'newsletter_consent': 'I want to receive news and special offers from Hotel Ruvubu',
    'send_message_button': 'Send Message',
    'how_to_find_us': 'How to Find Us',
    'address_label': 'Address',
    'address_details': 'Hotel Ruvubu, Cankuzo\nBuhumuza Province, Burundi',
    'landmarks_label': 'Landmarks',
    'landmarks_details': '25 km from Ruvubu National Park\n4 km from First Church of Muyaga\n25 km from Mishiha Hot Springs',
    'transport_label': 'Transport',
    'transport_details': 'Transfers from Bujumbura possible. Contact us to arrange transportation.',
    'quick_actions': 'Quick Actions',
    'book_room': 'Book a Room',
    'view_rooms': 'View our Rooms',
    'our_story': 'Our Story',
    'gallery': 'Gallery',
    'immediate_help': 'Need Immediate Help?',
    'reception_24_7': '24/7 reception ready to help you',
    'faq_title': 'FAQ',
    'frequently_asked_questions': 'Frequently Asked Questions',
    'faq_description': 'Common questions about our services and facilities',
    'faq1_question': 'How to get to Hotel Ruvubu from Bujumbura?',
    'faq1_answer': 'From Bujumbura International Airport, it\'s about 4 hours by road to Cankuzo. We offer transfers upon request. You can also take a bus to Cankuzo and then a taxi to the hotel.',
    'faq2_question': 'What payment methods do you accept?',
    'faq2_answer': 'Cash (BIF, USD), bank transfers, Visa, MasterCard. For international bookings, secure online options may be available.',
    'faq3_question': 'Do you offer guided tours of heritage sites?',
    'faq3_answer': 'Yes, guided tours of Muyaga, Musugi Cendajuru, Mishiha hot springs, and Ruvubu National Park. Local guides, transportation, and meals available.',
    'faq4_question': 'What facilities for business meetings?',
    'faq4_answer': 'Conference room (up to 100 people), WiFi, projector/sound system, whiteboards, catering, breakout rooms, and delegate accommodation.',
    'faq5_question': 'Do you handle dietary restrictions?',
    'faq5_answer': 'Yes. Vegetarian, vegan, gluten-free, halal, and other diets upon request. Indicate your needs when booking.',
    'learn_more_about_us': 'Learn more about us',
    'view_our_rooms': 'View our Rooms',
    'follow_us': 'Follow Us',
    'connect_on_social_media': 'Connect on Social Media',
    'social_media_description': 'Stay informed about our latest news, offers, and cultural events',
    'tripadvisor_handle': 'Read reviews',

    // Gallery page translations
    'all_categories': 'All',
    'categories_fetch_error': 'Failed to load categories',
    'gallery_fetch_error': 'Failed to load gallery items',
    'loading_gallery': 'Loading gallery...',
    'refresh_page': 'Refresh Page',
    'no_gallery_items': 'No gallery items found.',
    'load_more_photos': 'Load More Photos',
    'need_more_photos': 'Need more photos? Contact us',

    // Homepage Hero Section
    'hero_main_title': 'Hotel Ruvubu, Your Haven of Peace in Buhumuza',
    'hero_main_description': 'Discover Burundian hospitality at Hotel Ruvubu: spacious rooms, refined cuisine, and exceptional service in the heart of Buhumuza.',
    'free_wifi': 'Free WiFi',
    'restaurant': 'Restaurant',
    'gardens': 'Gardens',
    'book_now_hero': 'Book Now',
    'discover_our_rooms': 'Discover Our Rooms',
    'comfortable_rooms': 'Comfortable Rooms',
    'km_from_national_park': 'Km from National Park',
    'tourist_sites': 'Tourist Sites',
    'exceptional_service': 'Exceptional Service',
    'warm_welcome_service': 'A warm welcome and impeccable service. Hotel Ruvubu truly embodies the spirit of Buhumuza.',

    // Homepage About Section
    'welcome_to_hotel': 'Welcome to Hotel Ruvubu',
    'your_haven_of_peace': 'Your haven of peace in Cankuzo.',
    'about_description_1': 'Nestled in Buhumuza, Hotel Ruvubu is your refuge in the heart of Burundi\'s cultural and natural treasures.',
    'about_description_2': 'Spacious rooms, restaurant with Burundian and international flavors, friendly bar, gardens with artisanal lemonades, event spaces: everything for your comfort.',
    'about_description_3': 'Discover the legendary hospitality of Buhumuza at every moment of your stay.',
    'authenticity': 'Authenticity',
    'local_hospitality': 'Local Hospitality',
    '24_7': '24/7',
    'customer_service': 'Customer Service',
    'premium_services': 'Premium Services',
    'learn_more': 'Learn More',
    'view_rooms': 'View Rooms',
    'number_one_hotel': 'N°1',
    'hotel_in_cankuzo': 'Hotel in\nCankuzo',

    // Homepage Amenities Section
    'services': 'Services',
    'our_premium_facilities': 'Our Premium Facilities',
    'professional_restaurant': 'Professional Restaurant',
    'professional_restaurant_desc': 'Taste genuine Burundian specialties and flavors from our international menu, prepared with fresh and local products.',
    'qualified_chefs': 'Qualified Chefs',
    'local_specialties': 'Local Specialties',
    'magnificent_gardens': 'Magnificent Gardens',
    'magnificent_gardens_desc': 'Escape to our landscaped gardens and savor our delicious lemonades in a green and soothing setting.',
    'green_spaces': 'Green Spaces',
    'relaxation_areas': 'Relaxation Areas',
    'event_halls': 'Event Halls',
    'event_halls_desc': 'Conferences, weddings, and custom events with support from our professional team.',
    'wedding_hall': 'Wedding Hall',
    'conference_rooms': 'Conference Rooms',
    'tourist_services': 'Tourist Services',
    'tourist_services_desc': 'Discover the region with our expert guides: historical sites, natural wonders like the Ruvubu nature reserve.',
    'cultural_circuits': 'Cultural Circuits',
    'nature_excursions': 'Nature Excursions',
    'modern_bar': 'Modern Bar',
    'modern_bar_desc': 'Enjoy our artisanal lemonades, local drinks, and cocktails in our bar with a friendly atmosphere.',
    'premium_drinks': 'Premium Drinks',
    'modern_ambiance': 'Modern Ambiance',
    'warm_hospitality': 'Warm Hospitality',
    'warm_hospitality_desc': 'Discover the legendary hospitality of Buhumuza through our team dedicated to your comfort and an unforgettable stay.',
    'service_24_7': 'Service 24/7',
    'warm_welcome': 'Warm Welcome',

    // Homepage Rooms Section
    'accommodation': 'Accommodation',
    'your_comfortable_base_home': 'Your Comfortable Base',
    'quality_accommodation_comfort': 'Quality accommodation and comfort in the heart of Buhumuza',
    'per_night': '/night',
    'sqm': 'm²',
    'discover_all_rooms': 'Discover All Our Rooms',

    // Homepage Offers Section
    'offers': 'Offers',
    'discovery_packages': 'Discovery Packages',
    'special_offers_description': 'Special offers to discover the region and its wonders',
    'cultural_circuit': 'CULTURAL CIRCUIT',
    'buhumuza_heritage_circuit': 'Buhumuza Heritage Circuit',
    'heritage_circuit_desc': 'Includes accommodation, guided tours to Muyaga, Musugi Cendajuru, Mishiha hot springs, and lunch with local cuisine.',
    'valid_all_year': 'Valid all year',
    'contact_for_prices': 'Contact for prices',
    'nature_culture': 'NATURE & CULTURE',
    'park_culture_combo': 'Park & Culture Combo',
    'park_culture_combo_desc': 'Safari at Ruvubu Park and cultural sites combo. Includes park fees, guided tours, accommodation, and all meals.',
    'best_may_october': 'Best May - October',
    'events': 'EVENTS',
    'wedding_event_package': 'Wedding & Event Package',
    'wedding_event_package_desc': 'Complete package including hall rental, professional catering, guest accommodation, and materials for traditional ceremony.',
    'book_3_months_advance': 'Book 3 months in advance',
    'custom_quote_on_request': 'Custom quote on request',
    'get_quote': 'Get a Quote',
    'reserve': 'Reserve',

    // Homepage CTA Section
    'experience_buhumuza_hospitality': 'Experience Buhumuza Hospitality',
    'cta_description': 'Experience the Burundian spirit at Hotel Ruvubu: comfort, gastronomy, and privileged access to the region\'s natural treasures.',
    'spacious_comfortable_rooms': 'Spacious and comfortable rooms',
    'burundian_international_cuisine': 'Burundian and international cuisine',
    'bar_landscaped_gardens': 'Bar and landscaped gardens',
    'event_conference_spaces': 'Spaces for events and conferences',
    'excursions_ruvubu_park': 'Excursions to Ruvubu Park',
    'reserve_now': 'Reserve Now',
    'contact_us_cta': 'Contact Us',
    'nature_culture_badge': 'Nature & Culture',
    'to_discover': 'To Discover',

    // Homepage Gallery Section
    'spacious_room': 'Spacious room',
    'cultural_experience': 'Cultural Experience',
    'discover_more_photos': 'Discover More Photos',
    'close': 'Close',
    'click_outside_or_esc': 'Click outside the image or press Escape to close',
    'luxury_room': 'Luxury room',

    "booking": "Booking",
  "reservation": "Reservation",
  "book_your_stay": "Book Your Stay",
  "select_room": "Select Room",
  "guest_details": "Guest Details",
  "select_dates": "Select Dates",
  "check_in": "Check-in",
  "check_out": "Check-out",
  "guests": "Guests",
  "adults": "Adults",
  "children": "Children",
  "available_rooms": "Available Rooms",
  "reviews": "Reviews",
  "per_night": "per night",
  "standard_room_description": "A comfortable room with all essential amenities for a pleasant stay.",
  "included_amenities": "Included Amenities",
  "guest_information": "Guest Information",
  "first_name": "First Name",
  "last_name": "Last Name",
  "email_address": "Email Address",
  "phone_number": "Phone Number",
  "special_requests": "Special Requests",
  "special_requests_placeholder": "Any special requests or requirements...",
  "payment_information": "Payment Information",
  "cardholder_name": "Cardholder Name",
  "card_number": "Card Number",
  "expiry_date": "Expiry Date",
  "cvv": "CVV",
  "booking_summary": "Booking Summary",
  "nights": "nights",
  "taxes_fees": "Taxes & Fees",
  "total": "Total",
  "includes_taxes": "Includes all taxes and fees",
  "secure_booking": "Secure Booking",
  "secure_booking_description": "Your payment information is encrypted and secure. We never store your card details.",
  "continue_to_details": "Continue to Details",
  "complete_booking": "Complete Booking",
  "free_cancellation": "Free cancellation up to 48 hours before check-in",
  "modify_selection": "Modify Selection",
  "back_to_rooms": "Back to Room Selection",
  "check_in_out_times": "Check-in & Check-out Times",
  "need_help_booking": "Need Help with Your Booking?",
  "booking_assistance_description": "Our team is available 24/7 to assist you with your reservation. Contact us for any questions or special arrangements.",
  "call_us": "Call Us",
  "contact_us": "Contact Us",
  "rooms": "Rooms",
  "booking_confirmation_message": "Thank you for your booking! A confirmation email has been sent to your email address.",
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Check localStorage for saved language preference
    const saved = localStorage.getItem('preferredLanguage');
    return (saved === 'fr' || saved === 'en') ? saved : 'fr';
  });

  // Save language preference
  useEffect(() => {
    localStorage.setItem('preferredLanguage', language);
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || key;
    
    // Replace parameters if provided
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        text = text.replace(`{${param}}`, String(value));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};