import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  fr: {
    // Header translations
    'home': 'Accueil',
    'rooms': 'Chambres',
    'dining': 'Restaurant',
    'about': 'À Propos',
    'gallery': 'Galerie',
    'contact': 'Contact',
    'book_now': 'Réserver',
    'book_now_mobile': 'Réserver Maintenant',
    'hotel_ruvubu': 'Hôtel Ruvubu',
    'buhumuza_cankuzo': 'Buhumuza, Cankuzo',
    
    // Restaurant page translations
    'restaurant_bar': 'Restaurant & Bar',
    'dining_at_buhumuza': 'Restauration à Buhumuza',
    'dining_description': 'Cuisine burundaise authentique et spécialités internationales, préparées avec des produits sélectionnés. Bar lounge moderne, boissons maison et paniers-repas sur demande.',
    'local_international_cuisine': 'Cuisine locale et internationale',
    'lounge_bar_lemonades': 'Bar lounge & limonades artisanales',
    'picnic_baskets': 'Paniers-repas pour vos excursions',
    'cuisine_quote': 'Une cuisine adaptée à tous les goûts.',
    'our_menu': 'Notre Carte',
    'select_category': 'Sélectionnez une catégorie pour explorer nos saveurs',
    'all': 'Tout',
    'burundian': 'Burundais',
    'international': 'International',
    'special': 'Spécial',
    'previous': 'Précédent',
    'next': 'Suivant',
    'page_of': 'Page {current} sur {total}',
    'no_items': 'Aucun élément de menu disponible pour cette catégorie.',
    'thirsty_after_visits': 'Envie de fraîcheur après vos visites ?',
    'bar_description': 'Découvrez notre bar moderne et nos limonades artisanales après Muyaga, Mishiha ou le Parc Ruvubu.',
    'book_table': 'Réserver une Table',
    'view_bar': 'Voir le Bar',
    'error': 'Erreur',
    'retry': 'Réessayer',
    'loading': 'Chargement...',

    // About page translations
    'about_us': 'À propos',
    'our_heritage_history': 'Notre Patrimoine & Histoire',
    'our_story': 'Notre Histoire',
    'heritage_hospitality': 'Patrimoine & Hospitalité',
    'hero_title': 'Plus qu\'un hôtel, un pont vers l\'âme de Buhumuza.',
    'hero_description_1': 'L\'Hôtel Ruvubu incarne l\'esprit d\'apaisement de Buhumuza. Un refuge pour voyageurs en quête de sérénité et d\'immersion culturelle burundaise.',
    'hero_description_2': 'Porte d\'entrée vers les trésors de l\'Est : église de Muyaga, eaux thermales de Mishiha et Parc National de la Ruvubu. Histoire, nature et culture à portée de main.',
    'hero_description_3': 'Chambres confortables, cuisine raffinée, bar convivial, jardins paisibles : l\'hospitalité burundaise dans chaque détail.',
    'inauguration': 'Inauguration',
    'opening_title': 'Ouverture Officielle',
    'opening_description': 'L\'Hôtel Ruvubu devient la référence de l\'hospitalité à Cankuzo.',
    'tours_title': 'Circuits Touristiques',
    'tours_description': 'Excursions vers Muyaga, Mishiha et le Parc de la Ruvubu avec guides locaux.',
    'discover_region': 'Découvrir la Région',
    'watch_video': 'Voir la Vidéo',
    'excellence': 'L\'Excellence',
    'serving_your_stay': 'Au Service de votre Séjour',
    'gastronomy_title': 'Gastronomie Professionnelle',
    'gastronomy_description': 'Fusion de saveurs burundaises et internationales par nos chefs qualifiés.',
    'cultural_experiences_title': 'Expériences Culturelles',
    'cultural_experiences_description': 'Excursions vers sites historiques et naturels avec accès privilégié aux guides locaux.',
    'burundian_lifestyle_title': 'Art de Vivre Burundais',
    'burundian_lifestyle_description': 'Jardins paysagers et espaces pour mariages, conférences et réceptions.',
    'discover': 'Découvrir',
    'buhumuza_treasures': 'Trésors de Buhumuza',
    'explore_jewels': 'Explorez les joyaux entourant l\'Hôtel Ruvubu',
    'historical_badge': 'Historique',
    'wellness_badge': 'Bien-être',
    'culture_badge': 'Culture',
    'adventure_badge': 'Aventure',
    'muyaga_church_title': 'Première Église de Muyaga',
    'muyaga_church_description': 'Berceau du catholicisme burundais depuis 1889. Architecture coloniale et spiritualité.',
    'muyaga_church_distance': 'À proximité immédiate',
    'mishiha_hot_springs_title': 'Eaux Chaudes de Mishiha',
    'mishiha_hot_springs_description': 'Sources géothermiques naturelles aux vertus curatives et relaxantes.',
    'mishiha_hot_springs_distance': 'Excursion d\'une journée',
    'musugi_cendajuru_title': 'Musugi Cendajuru',
    'musugi_cendajuru_description': 'Site historique de l\'arrivée des premiers missionnaires, mémoire vivante de la région.',
    'musugi_cendajuru_distance': 'Accès facilité',
    'ruvubu_park_title': 'Parc National de la Ruvubu',
    'ruvubu_park_description': 'Safari et observation de la faune : hippopotames, crocodiles, buffles et avifaune.',
    'ruvubu_park_distance': 'Circuit guidé disponible',
    'book_stay_circuit': 'Réserver mon séjour & circuit',
    'garden_image_alt': 'Jardins paisibles de l\'Hôtel Ruvubu à Cankuzo',
    'room_image_alt': 'Chambre spacieuse',

    // Rooms page translations
    'rooms': 'Chambres',
    'your_comfortable_base': 'Votre Base Confortable',
    'loading_rooms': 'Chargement des chambres...',
    'loading_error': 'Erreur de chargement',
    'fetch_error': 'Échec du chargement des chambres',
    'generic_error': 'Une erreur est survenue',
    'price_range': 'Fourchette de Prix',
    'all_prices': 'Tous les Prix',
    'under_50k': 'Moins de 50 000',
    '50k_100k': '50 000 - 100 000',
    '100k_150k': '100 000 - 150 000',
    'over_150k': '150 000+',
    'guest_capacity': 'Capacité d\'Accueil',
    'any_capacity': 'Toute Capacité',
    '1_person': '1 Personne',
    '1_2_people': '1-2 Personnes',
    '3_4_people': '3-4 Personnes',
    '5_people': '5+ Personnes',
    'room_type': 'Type de Chambre',
    'all_rooms': 'Toutes les Chambres',
    'suite': 'Suite',
    'standard_room': 'Chambre Standard',
    'family_room': 'Chambre Familiale',
    'twin_room': 'Chambre Twin',
    'bungalow': 'Bungalow Groupe',
    'sort_by': 'Trier Par',
    'most_popular': 'Les Plus Populaires',
    'price_low_high': 'Prix : Croissant',
    'price_high_low': 'Prix : Décroissant',
    'customer_rating': 'Évaluation Client',
    'room_size': 'Taille de Chambre',
    'people': 'pers.',
    'default_room_description': 'Chambre confortable avec toutes les commodités nécessaires.',
    'reviews': 'avis',
    'no_reviews_yet': 'Pas encore d\'avis',
    'book': 'Réserver',
    'view_details': 'Voir détails',
    'no_rooms_match': 'Aucune chambre ne correspond',
    'adjust_filters': 'Ajustez vos filtres pour voir plus d\'options.',
    'reset_filters': 'Réinitialiser les filtres',
    'view_more_rooms': 'Voir Plus de Chambres',

     // Contact page translations
    'contact': 'Contact',
    'contact_us': 'Nous Contacter',
    'connect_with_hotel': 'Connectez-vous avec l\'Hôtel Ruvubu',
    'contact_description': 'Votre porte d\'entrée vers l\'hospitalité de Buhumuza et les expériences du patrimoine culturel.',
    'map_title': 'Emplacement de l\'Hôtel Ruvubu à Cankuzo, Burundi',
    'open_in_google_maps': 'Ouvrir dans Google Maps',
    'location_title': 'Notre Localisation',
    'location_line1': 'Cankuzo, Province de Buhumuza',
    'location_line2': 'Burundi, Afrique de l\'Est',
    'location_note': 'Près de l\'entrée du Parc National de la Ruvubu',
    'call_us_title': 'Appelez-nous',
    'phone_line1': '+257 66 307 160',
    'phone_line2': '+257 69 671 060',
    'phone_note': 'WhatsApp disponible',
    'email_title': 'Envoyez-nous un Email',
    'email_line1': 'ruvubuhotel@gmail.com',
    'email_note': 'Réponse sous 24 heures',
    'send_message_title': 'Envoyez-nous un Message',
    'send_message_description': 'Des questions sur nos chambres, visites patrimoniales ou installations événementielles ? Remplissez le formulaire et nous répondons sous 24h.',
    'full_name': 'Nom Complet',
    'email_address': 'Adresse Email',
    'phone_number': 'Numéro de Téléphone',
    'phone_placeholder': '+257 79 123 456',
    'country': 'Pays',
    'subject': 'Sujet',
    'select_subject': 'Sélectionnez un sujet',
    'room_booking': 'Réservation de Chambre',
    'heritage_tour_request': 'Demande de Visite Patrimoniale',
    'event_conference': 'Événement & Conférence',
    'restaurant_booking': 'Réservation Restaurant',
    'group_booking': 'Réservation de Groupe',
    'general_inquiry': 'Demande Générale',
    'feedback': 'Retour d\'Expérience',
    'your_message': 'Votre Message',
    'message_placeholder': 'Dites-nous comment nous pouvons vous aider à vivre l\'hospitalité de Buhumuza...',
    'newsletter_consent': 'Je souhaite recevoir les nouvelles et offres spéciales de l\'Hôtel Ruvubu',
    'send_message_button': 'Envoyer le Message',
    'how_to_find_us': 'Comment Nous Trouver',
    'address_label': 'Adresse',
    'address_details': 'Hôtel Ruvubu, Cankuzo\nProvince de Buhumuza, Burundi',
    'landmarks_label': 'Points de repère',
    'landmarks_details': '25 km du Parc National de la Ruvubu\n4 km de la Première Église de Muyaga\n25 km des Sources Chaudes de Mishiha',
    'transport_label': 'Transport',
    'transport_details': 'Transferts depuis Bujumbura possibles. Contactez-nous pour organiser le transport.',
    'quick_actions': 'Actions Rapides',
    'book_room': 'Réserver une Chambre',
    'view_rooms': 'Voir nos Chambres',
    'our_story': 'Notre Histoire',
    'gallery': 'Galerie',
    'immediate_help': 'Besoin d\'Aide Immédiate ?',
    'reception_24_7': 'Réception 24/7 prête à vous aider',
    'faq_title': 'FAQ',
    'frequently_asked_questions': 'Questions Fréquemment Posées',
    'faq_description': 'Questions courantes sur nos services et installations',
    'faq1_question': 'Comment se rendre à l\'Hôtel Ruvubu depuis Bujumbura ?',
    'faq1_answer': 'Depuis l\'Aéroport International de Bujumbura, il y a environ 4 heures de route jusqu\'à Cankuzo. Nous proposons des transferts sur demande. Vous pouvez aussi prendre un bus jusqu\'à Cankuzo puis un taxi jusqu\'à l\'hôtel.',
    'faq2_question': 'Quels modes de paiement acceptez-vous ?',
    'faq2_answer': 'Espèces (BIF, USD), virements bancaires, Visa, MasterCard. Pour les réservations internationales, des options en ligne sécurisées peuvent être proposées.',
    'faq3_question': 'Proposez-vous des visites guidées des sites patrimoniaux ?',
    'faq3_answer': 'Oui, visites guidées de Muyaga, Musugi Cendajuru, sources chaudes de Mishiha et Parc National de la Ruvubu. Guides locaux, transport et repas disponibles.',
    'faq4_question': 'Quelles installations pour les réunions d\'affaires ?',
    'faq4_answer': 'Salle de conférence (jusqu\'à 100 pers), WiFi, projecteur/son, paperboards, restauration, salles de sous-groupes et hébergement des délégués.',
    'faq5_question': 'Gérez-vous les restrictions alimentaires ?',
    'faq5_answer': 'Oui. Régimes végétarien, végétalien, sans gluten, halal et autres sur demande. Indiquez vos besoins lors de la réservation.',
    'learn_more_about_us': 'En savoir plus sur nous',
    'view_our_rooms': 'Voir nos Chambres',
    'follow_us': 'Suivez-nous',
    'connect_on_social_media': 'Connectez-vous sur les Réseaux Sociaux',
    'social_media_description': 'Restez informé de nos dernières nouvelles, offres et événements culturels',
    'tripadvisor_handle': 'Lire les avis',

  },
  en: {
    // Header translations
    'home': 'Home',
    'rooms': 'Rooms',
    'dining': 'Dining',
    'about': 'About',
    'gallery': 'Gallery',
    'contact': 'Contact',
    'book_now': 'Book Now',
    'book_now_mobile': 'Book Now',
    'hotel_ruvubu': 'Hotel Ruvubu',
    'buhumuza_cankuzo': 'Buhumuza, Cankuzo',
    
    // Restaurant page translations
    'restaurant_bar': 'Restaurant & Bar',
    'dining_at_buhumuza': 'Dining at Buhumuza',
    'dining_description': 'Authentic Burundian cuisine and international specialties, prepared with carefully selected products. Modern lounge bar, house-made drinks, and picnic baskets available upon request.',
    'local_international_cuisine': 'Local and international cuisine',
    'lounge_bar_lemonades': 'Lounge bar & artisanal lemonades',
    'picnic_baskets': 'Picnic baskets for your excursions',
    'cuisine_quote': 'A cuisine to suit all tastes.',
    'our_menu': 'Our Menu',
    'select_category': 'Select a category to explore our flavors',
    'all': 'All',
    'burundian': 'Burundian',
    'international': 'International',
    'special': 'Special',
    'previous': 'Previous',
    'next': 'Next',
    'page_of': 'Page {current} of {total}',
    'no_items': 'No menu items available for this category.',
    'thirsty_after_visits': 'Thirsty after your visits?',
    'bar_description': 'Discover our modern bar and artisanal lemonades after visiting Muyaga, Mishiha or Ruvubu Park.',
    'book_table': 'Book a Table',
    'view_bar': 'View the Bar',
    'error': 'Error',
    'retry': 'Retry',
    'loading': 'Loading...',

    // About page translations
    'about_us': 'About',
    'our_heritage_history': 'Our Heritage & History',
    'our_story': 'Our Story',
    'heritage_hospitality': 'Heritage & Hospitality',
    'hero_title': 'More than a hotel, a bridge to the soul of Buhumuza.',
    'hero_description_1': 'Hotel Ruvubu embodies the calming spirit of Buhumuza. A refuge for travelers seeking serenity and Burundian cultural immersion.',
    'hero_description_2': 'Gateway to the treasures of the East: Muyaga Church, Mishiha hot springs, and Ruvubu National Park. History, nature, and culture at your fingertips.',
    'hero_description_3': 'Comfortable rooms, refined cuisine, cozy bar, peaceful gardens: Burundian hospitality in every detail.',
    'inauguration': 'Inauguration',
    'opening_title': 'Official Opening',
    'opening_description': 'Hotel Ruvubu becomes the hospitality reference in Cankuzo.',
    'tours_title': 'Tourist Circuits',
    'tours_description': 'Excursions to Muyaga, Mishiha, and Ruvubu Park with local guides.',
    'discover_region': 'Discover the Region',
    'watch_video': 'Watch Video',
    'excellence': 'Excellence',
    'serving_your_stay': 'Serving Your Stay',
    'gastronomy_title': 'Professional Gastronomy',
    'gastronomy_description': 'Fusion of Burundian and international flavors by our qualified chefs.',
    'cultural_experiences_title': 'Cultural Experiences',
    'cultural_experiences_description': 'Excursions to historical and natural sites with privileged access to local guides.',
    'burundian_lifestyle_title': 'Burundian Lifestyle',
    'burundian_lifestyle_description': 'Landscaped gardens and spaces for weddings, conferences, and receptions.',
    'discover': 'Discover',
    'buhumuza_treasures': 'Buhumuza Treasures',
    'explore_jewels': 'Explore the jewels surrounding Hotel Ruvubu',
    'historical_badge': 'Historical',
    'wellness_badge': 'Wellness',
    'culture_badge': 'Culture',
    'adventure_badge': 'Adventure',
    'muyaga_church_title': 'First Church of Muyaga',
    'muyaga_church_description': 'Birthplace of Burundian Catholicism since 1889. Colonial architecture and spirituality.',
    'muyaga_church_distance': 'In immediate proximity',
    'mishiha_hot_springs_title': 'Mishiha Hot Springs',
    'mishiha_hot_springs_description': 'Natural geothermal springs with curative and relaxing properties.',
    'mishiha_hot_springs_distance': 'One-day excursion',
    'musugi_cendajuru_title': 'Musugi Cendajuru',
    'musugi_cendajuru_description': 'Historical site of the arrival of the first missionaries, living memory of the region.',
    'musugi_cendajuru_distance': 'Easy access',
    'ruvubu_park_title': 'Ruvubu National Park',
    'ruvubu_park_description': 'Safari and wildlife observation: hippopotamuses, crocodiles, buffaloes, and avifauna.',
    'ruvubu_park_distance': 'Guided tour available',
    'book_stay_circuit': 'Book my stay & tour',
    'garden_image_alt': 'Peaceful gardens of Hotel Ruvubu in Cankuzo',
    'room_image_alt': 'Spacious room',

     // Rooms page translations
    // 'rooms': 'Rooms',
    'your_comfortable_base': 'Your Comfortable Base',
    'loading_rooms': 'Loading rooms...',
    'loading_error': 'Loading Error',
    'fetch_error': 'Failed to fetch rooms',
    'generic_error': 'An error occurred',
    'price_range': 'Price Range',
    'all_prices': 'All Prices',
    'under_50k': 'Under 50,000',
    '50k_100k': '50,000 - 100,000',
    '100k_150k': '100,000 - 150,000',
    'over_150k': '150,000+',
    'guest_capacity': 'Guest Capacity',
    'any_capacity': 'Any Capacity',
    '1_person': '1 Person',
    '1_2_people': '1-2 People',
    '3_4_people': '3-4 People',
    '5_people': '5+ People',
    'room_type': 'Room Type',
    'all_rooms': 'All Rooms',
    'suite': 'Suite',
    'standard_room': 'Standard Room',
    'family_room': 'Family Room',
    'twin_room': 'Twin Room',
    'bungalow': 'Group Bungalow',
    'sort_by': 'Sort By',
    'most_popular': 'Most Popular',
    'price_low_high': 'Price: Low to High',
    'price_high_low': 'Price: High to Low',
    'customer_rating': 'Customer Rating',
    'room_size': 'Room Size',
    'people': 'people',
    'default_room_description': 'Comfortable room with all necessary amenities.',
    'reviews': 'reviews',
    'no_reviews_yet': 'No reviews yet',
    'book': 'Book',
    'view_details': 'View details',
    'no_rooms_match': 'No rooms match',
    'adjust_filters': 'Adjust your filters to see more options.',
    'reset_filters': 'Reset filters',
    'view_more_rooms': 'View More Rooms',

    // Contact page translations
    'contact': 'Contact',
    'contact_us': 'Contact Us',
    'connect_with_hotel': 'Connect with Hotel Ruvubu',
    'contact_description': 'Your gateway to Buhumuza hospitality and cultural heritage experiences.',
    'map_title': 'Location of Hotel Ruvubu in Cankuzo, Burundi',
    'open_in_google_maps': 'Open in Google Maps',
    'location_title': 'Our Location',
    'location_line1': 'Cankuzo, Buhumuza Province',
    'location_line2': 'Burundi, East Africa',
    'location_note': 'Near the entrance to Ruvubu National Park',
    'call_us_title': 'Call Us',
    'phone_line1': '+257 66 307 160',
    'phone_line2': '+257 69 671 060',
    'phone_note': 'WhatsApp available',
    'email_title': 'Send Us an Email',
    'email_line1': 'ruvubuhotel@gmail.com',
    'email_note': 'Response within 24 hours',
    'send_message_title': 'Send Us a Message',
    'send_message_description': 'Questions about our rooms, heritage tours, or event facilities? Fill out the form and we\'ll respond within 24 hours.',
    'full_name': 'Full Name',
    'email_address': 'Email Address',
    'phone_number': 'Phone Number',
    'phone_placeholder': '+257 79 123 456',
    'country': 'Country',
    'subject': 'Subject',
    'select_subject': 'Select a subject',
    'room_booking': 'Room Booking',
    'heritage_tour_request': 'Heritage Tour Request',
    'event_conference': 'Event & Conference',
    'restaurant_booking': 'Restaurant Booking',
    'group_booking': 'Group Booking',
    'general_inquiry': 'General Inquiry',
    'feedback': 'Feedback',
    'your_message': 'Your Message',
    'message_placeholder': 'Tell us how we can help you experience Buhumuza hospitality...',
    'newsletter_consent': 'I want to receive news and special offers from Hotel Ruvubu',
    'send_message_button': 'Send Message',
    'how_to_find_us': 'How to Find Us',
    'address_label': 'Address',
    'address_details': 'Hotel Ruvubu, Cankuzo\nBuhumuza Province, Burundi',
    'landmarks_label': 'Landmarks',
    'landmarks_details': '25 km from Ruvubu National Park\n4 km from First Church of Muyaga\n25 km from Mishiha Hot Springs',
    'transport_label': 'Transport',
    'transport_details': 'Transfers from Bujumbura possible. Contact us to arrange transportation.',
    'quick_actions': 'Quick Actions',
    'book_room': 'Book a Room',
    'view_rooms': 'View our Rooms',
    'our_story': 'Our Story',
    'gallery': 'Gallery',
    'immediate_help': 'Need Immediate Help?',
    'reception_24_7': '24/7 reception ready to help you',
    'faq_title': 'FAQ',
    'frequently_asked_questions': 'Frequently Asked Questions',
    'faq_description': 'Common questions about our services and facilities',
    'faq1_question': 'How to get to Hotel Ruvubu from Bujumbura?',
    'faq1_answer': 'From Bujumbura International Airport, it\'s about 4 hours by road to Cankuzo. We offer transfers upon request. You can also take a bus to Cankuzo and then a taxi to the hotel.',
    'faq2_question': 'What payment methods do you accept?',
    'faq2_answer': 'Cash (BIF, USD), bank transfers, Visa, MasterCard. For international bookings, secure online options may be available.',
    'faq3_question': 'Do you offer guided tours of heritage sites?',
    'faq3_answer': 'Yes, guided tours of Muyaga, Musugi Cendajuru, Mishiha hot springs, and Ruvubu National Park. Local guides, transportation, and meals available.',
    'faq4_question': 'What facilities for business meetings?',
    'faq4_answer': 'Conference room (up to 100 people), WiFi, projector/sound system, whiteboards, catering, breakout rooms, and delegate accommodation.',
    'faq5_question': 'Do you handle dietary restrictions?',
    'faq5_answer': 'Yes. Vegetarian, vegan, gluten-free, halal, and other diets upon request. Indicate your needs when booking.',
    'learn_more_about_us': 'Learn more about us',
    'view_our_rooms': 'View our Rooms',
    'follow_us': 'Follow Us',
    'connect_on_social_media': 'Connect on Social Media',
    'social_media_description': 'Stay informed about our latest news, offers, and cultural events',
    'tripadvisor_handle': 'Read reviews',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Check localStorage for saved language preference
    const saved = localStorage.getItem('preferredLanguage');
    return (saved === 'fr' || saved === 'en') ? saved : 'fr';
  });

  // Save language preference
  useEffect(() => {
    localStorage.setItem('preferredLanguage', language);
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || key;
    
    // Replace parameters if provided
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        text = text.replace(`{${param}}`, String(value));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};